POST http://localhost:8092/v1/reviews
Content-Type: application/json

{
  "reviewId": "1",
  "movieInfoId": 1,
  "comment": "Amazing movie with a lot of actions",
  "rating":9.00
}

###
GET http://localhost:8092/v1/reviews
Content-Type: application/json

###
GET http://localhost:8092/v1/reviews?movieInfoId=1
Content-Type: application/json

###
GET http://localhost:8092/v1/reviews?movieInfoId=2
Content-Type: application/json

###
PUT http://localhost:8092/v1/reviews/1
Content-Type: application/json

{
  "reviewId": "1",
  "movieInfoId": 5,
  "comment": "updated_comment_73a69b25ada9",
  "rating": 50.5
}

###
PUT http://localhost:8092/v1/reviews/999
Content-Type: application/json

{
  "reviewId": "1",
  "movieInfoId": 5,
  "comment": "updated_comment_73a69b25ada9",
  "rating": 50.5
}

###
DELETE http://localhost:8092/v1/reviews/1

